### ISSUE TITLE
Authentication module

### ISSUE THREAD

**Issue by ShintaroNippon** [notrab/create-react-app-redux#15]
It is possible helping me developing a auth system recurring to a fake api for the moment like
https://reqres.in/

where i have the login auth with redux
and then a midleware to check if route is logged in or not

i would like an implementation of this from a pro

thanks in advance
carlos vieira

**Comment by notrab** [comment]
Hey

I'll try and create a tutorial within the next week to guide you through authentication & create react app 👍

**Comment by ShintaroNippon** [comment]
thanks
carlos vieira

**Comment by notrab** [comment]
No time right now but still have plans to do this @ShintaroNippon
