### ISSUE TITLE
Dockerfile missing

### ISSUE THREAD

**Issue by aakash176** [notrab/create-react-app-redux#172]
Dockerfile can help other developers easily create an image of your application. I have noticed that there is Dockerfile missing from the codebase, So could you please assign me to create Dockerfile for this application.

**Comment by notrab** [comment]
Hey you can just create a PR to this repo, however, this should be considered outdated now. There are much better defaults for React (Vite,Next,Remix) so this tutorial/starter might not be that helpful in 2023.
