### ISSUE TITLE
remove routing

### ISSUE THREAD

**Issue by csomakk** [notrab/create-react-app-redux#70]
Hi! Any idea how can i remove routing, so http://server/mycustomfolder/index.html would work? I tried to 
- remove router 
- edit basename on createHistory
but those didn't help

Any idea appreciated

**Comment by csomakk** [comment]
.

**Comment by vipinlahoti** [comment]
@csomakk not sure what you mean by remove routing, you can remove "react-router-dom" package and its corresponding components.
